CI: AlmaLinux Kitten 10 support #2

diff --git a/.github/workflows/almalinux-compose-test-x86_64.yml b/.github/workflows/almalinux-compose-test-x86_64.yml
--- a/.github/workflows/almalinux-compose-test-x86_64.yml
+++ b/.github/workflows/almalinux-compose-test-x86_64.yml
@@ -155,7 +155,9 @@ jobs:
     - name: Create 'yq' script to get failed tests
       run: |
         cat <<'EOF'>./yq.sh
-        yq --no-doc '.[] | select(.result == "fail" or .result == "error") | .name' ${{ env.tmt_run_dir }}/plans/legacy/execute/results.yaml ${{ env.tmt_run_dir }}/plans/ng/execute/results.yaml > ${{ env.tmt_run_dir }}/tests_failed.txt
+        yq --no-doc '.[] | select(.result == "fail" or .result == "error") | .name' ${{ env.tmt_run_dir }}/plans/legacy/execute/results.yaml ${{ env.tmt_run_dir }}/plans/ng/execute/results.yaml > ${{ env.tmt_run_dir }}/tests_failed.txt || exit 1
+        echo "[Debug] $(cat ${{ env.tmt_run_dir }}/tests_failed.txt)"
+        echo "$(grep -B 1 'result: fail' ${{ env.tmt_run_dir }}/plans/legacy/execute/results.yaml ${{ env.tmt_run_dir }}/plans/ng/execute/results.yaml)"
         EOF
 
     - name: Run vagrant up
